### ISSUE TITLE
[BUG] Double hooking forwards cancels gas too long

### ISSUE THREAD

**Issue by Acros5542** [AoTTG-2/AoTTG-2#636]
**Describe the bug**
Even in AoTTG1 double hooking (with Q+E simultaneously, not the actual double-hook keybind) forwards will temporarily stop the gas animation; however, as per #33 merging, double hooking forwards now cancels your gas itself and for too long, making double hooking forwards act as a form of g-stopping, with it giving far less speed than it should. This exact issue actually existed in older versions of AoTTG1 (fixed around the same time as the new titan models were implemented iirc).

**To Reproduce**
1. While holding gas, fire both hooks simultaneously into an object in front of you
2. Notice how your gas trail stops and you gain very little if any speed

**Expected behavior**
The effect of double hooking forwards stopping your gas should not last long enough to impact movement or negate the benefit of double hooking forwards to gain speed.

**Video**
https://youtu.be/SBRLyvp74CY

**Additional context**
I wouldn't approach this trying to tweak the numbers to make the current state of it match the old one, as I believe there's a root issue that when fixed will cause the interaction to behave properly again. Before #33 it was working properly if you want to compare the two.

**Contributor instructions**
1. Try to recreate the bug via the reported reproduction steps. If the bug can be reproduced, remove the investigation label. If the bug cannot be reproduced, please add a comment, attach "On Hold" label and inform the submitter that the bug cannot be reproduced. If there is no reply after 2 weeks, the issue can be closed.
2. Follow the default development team procedures (Create a new branch, apply your fix, create a pull request, submit new builds for testing team in dev squad)
3. Once testing team has confirmed the issue is resolved and the pull request is accepted, the issue can be closed.

**Comment by SlowDeepExhalation** [comment]
A comment--after testing to verify this, it does seem more common, but **it is not something fixed in RC.**  Double hooking something can still occasionally cancel gas in all mods I've played, unless you are either swinging blades at time of contact, playing AHSS, or canceling a gas burst.  I haven't verified the latter two in AoTTG 2 myself, but swinging blades does protect gas as in AoTTG1 mods.

**Comment by Acros5542** [comment]
@SlowDeepExhalation Yeah I noticed it appeared to still happen in AoTTG1 when testing this, but it definitely feels like the effect is stronger/longer lasting in AoTTG2. Here's a quick video comparing the two: https://youtu.be/9NxRkdAhoAA
I used Jean so they both should have the same Accel stat

**Comment by Acros5542** [comment]
Need to retest this now that we know ACCL was lower than we thought.
